Description: Production domain DNS rules

Parameters:
  HostedZoneStack:
    Type: String
    Default: sugg1144-infrastructure-hosted-zone-prod

  TTL:
    Type: Number
    Default: 172800

Resources:

  DevNSRecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Name:
        !Sub
        - 'dev.${DomainName}'
        - DomainName:
            Fn::ImportValue:
              !Sub '${HostedZoneStack}-name'
      HostedZoneId:
        Fn::ImportValue: !Sub '${HostedZoneStack}-id'
      Type: NS
      TTL: !Ref "TTL"
      ResourceRecords:
        - ns-368.awsdns-46.com
        - ns-1683.awsdns-18.co.uk
        - ns-559.awsdns-05.net
        - ns-1311.awsdns-35.org

  TxtRecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Name:
        Fn::ImportValue: !Sub '${HostedZoneStack}-name'
      HostedZoneId:
        Fn::ImportValue: !Sub '${HostedZoneStack}-id'
      Type: TXT
      TTL: 900
      ResourceRecords:
        - !Sub '"google-site-verification=17LS4y-I6gogxiZTxMyGSB2_5_kp49mS0bvc4mkXdR0"'
        - !Sub '"v=spf1 include:_spf.google.com include:amazonses.com ~all"'

  GoogleDKIMRecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Name:
        !Sub
        - 'google._domainkey.${DomainName}'
        - DomainName:
            Fn::ImportValue:
              !Sub '${HostedZoneStack}-name'
      HostedZoneId:
        Fn::ImportValue: !Sub '${HostedZoneStack}-id'
      Type: TXT
      TTL: !Ref "TTL"
      ResourceRecords:
        - '"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhPrVlIggfiXyunN89UjWYHIIWtIl7mXZ2NjbD7mP+aLWHSkMN1J8CDgqEajJgWzKDuexYytxklqolV0QyzKLCOJeON0TsIc33WdEHlSMxpAmIXlpemAg"'
        - '"OwdDjwIixDLQSlAc30/zq1w0PWof4X/UnEOFhpe8/nQ1xl1bq1dF+VALsag3is8P3ggAZc1RLp1SLPjti0ggEe9BhtN3QjambmJHtgS/Eq6jE5x8ztq8jU7lJBDWjYNkAPFpv1KxUPkVpZ9DyRms0Yd+B/E8BqR2N7Ckrg0cMjjlkJrs2P8jFqLfplThB6YPI+rCu6ih0tfQnBzZwKT/90fTAEXw372OMwIDAQAB"'

  DevCertificateRecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Name:
        !Sub
        - '_d59f000cfa44fae7c35ba67884400e3a.${DomainName}'
        - DomainName:
            Fn::ImportValue:
              !Sub '${HostedZoneStack}-name'
      HostedZoneId:
        Fn::ImportValue: !Sub '${HostedZoneStack}-id'
      Type: CNAME
      TTL: !Ref "TTL"
      ResourceRecords:
        - '_d2126089db63c742d6779d57106e3f7c.kirrbxfjtw.acm-validations.aws.'
